import streamlit as st
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from src.data_loader import load_data

st.set_page_config(
    page_title="PDF Report Generator",
    page_icon="📄",
    layout="wide"
)

st.title("PDF Report Generator")
st.write("Generate a downloadable PDF report for MPCE analysis.")

df = load_data()

def create_pdf_report():
    file_path = "mpce_analysis_report.pdf"

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    avg_mpce = df["mpce"].mean()
    avg_total = df["total_monthly_expenditure"].mean()
    avg_rural = df[df["sector_rural_urban"] == "Rural"]["mpce"].mean()
    avg_urban = df[df["sector_rural_urban"] == "Urban"]["mpce"].mean()

    highest_state = df.groupby("state")["mpce"].mean().idxmax()
    lowest_state = df.groupby("state")["mpce"].mean().idxmin()

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "MPCE Household Expenditure Analysis Report")

    c.setFont("Helvetica", 11)
    c.drawString(50, height - 85, "AI-Powered Household Expenditure Intelligence System")

    c.line(50, height - 100, width - 50, height - 100)

    y = height - 140

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "1. Dataset Summary")

    y -= 30
    c.setFont("Helvetica", 11)
    c.drawString(70, y, f"Total Households: {len(df)}")

    y -= 22
    c.drawString(70, y, f"Average MPCE: Rs. {avg_mpce:.2f}")

    y -= 22
    c.drawString(70, y, f"Average Total Monthly Expenditure: Rs. {avg_total:.2f}")

    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "2. Rural vs Urban Analysis")

    y -= 30
    c.setFont("Helvetica", 11)
    c.drawString(70, y, f"Average Rural MPCE: Rs. {avg_rural:.2f}")

    y -= 22
    c.drawString(70, y, f"Average Urban MPCE: Rs. {avg_urban:.2f}")

    y -= 22
    gap = avg_urban - avg_rural
    c.drawString(70, y, f"Urban-Rural MPCE Gap: Rs. {gap:.2f}")

    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "3. State-Level Insights")

    y -= 30
    c.setFont("Helvetica", 11)
    c.drawString(70, y, f"Highest MPCE State: {highest_state}")

    y -= 22
    c.drawString(70, y, f"Lowest MPCE State: {lowest_state}")

    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "4. Key Interpretation")

    y -= 30
    c.setFont("Helvetica", 11)
    c.drawString(70, y, "The system identifies rural-urban expenditure differences,")
    y -= 22
    c.drawString(70, y, "state-wise MPCE variation, and major household consumption patterns.")
    y -= 22
    c.drawString(70, y, "These insights can support socio-economic analysis and decision-making.")

    y -= 50
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Generated by MPCE Insight360")

    c.save()

    return file_path


if st.button("Generate PDF Report"):
    pdf_path = create_pdf_report()

    with open(pdf_path, "rb") as file:
        st.download_button(
            label="Download MPCE PDF Report",
            data=file,
            file_name="mpce_analysis_report.pdf",
            mime="application/pdf"
        )

    st.success("PDF report generated successfully.")